name: so-co2
channels:
- conda-forge
dependencies:
- aiohttp
- bokeh
- bottleneck
- cartopy
- cf_units
- cftime
- cmocean
- dask
- distributed
- dask-jobqueue
- dask-mpi
- esmpy
- fsspec
- intake
- intake-esm
- intake-xarray
- ipywidgets
- jupyter_contrib_nbextensions
- jupyter-book
- jupyterlab
- lmfit
- matplotlib
- metpy
- nc-time-axis
- ncar-jobqueue
- netcdf4
- numba
- numpy
- pandas
- pint
- pip
- pop-tools
- pytest
- python=3.7
- scipy
- seaborn
- seawater
- statsmodels
- toolz
- xarray
- xesmf
- xhistogram
- zarr
- pip:
  - git+https://github.com/matt-long/xpersist.git
